### ISSUE TITLE
Temperature stuck if no delay is added between readings

### ISSUE THREAD

**Issue by jarapablo** [YuriiSalimov/MAX6675_Thermocouple#1]
Hello, I am just getting into github so please accept my apologies if I am not proceeding correctly to report this bug.

I am just using this library (v1.1.0) with the Arduino IDE and an Arduino UNO. I coded my own program and realised that I was getting the same readings every single time. After some troubleshooting, I noticed the issue was happening because I had no delay(100) on my code (it was on the example files). 

I tested the Example files removing the delay(100) and I was able to reproduce the error. This is the output on the serial monitor:
Temperature: 25.50 C, 298.65 K, 77.90 F
Temperature: 25.50 C, 298.65 K, 77.90 F
Temperature: 25.50 C, 298.65 K, 77.90 F
Temperature: 25.50 C, 298.65 K, 77.90 F
Temperature: 25.50 C, 298.65 K, 77.90 F
Temperature: 25.50 C, 298.65 K, 77.90 F
Temperature: 25.50 C, 298.65 K, 77.90 F
Temperature: 25.50 C, 298.65 K, 77.90 F
Temperature: 25.50 C, 298.65 K, 77.90 F
Temperature: 25.50 C, 298.65 K, 77.90 F

I am guessing the required delay can be added to the library but I am not sure of where to put it myself (also still have to figure out how to contribute on GITHUB without breaking stuff).

Hopefully this information is useful and the bug can be fixed.

Best!

**Comment by suoapvs** [comment]
**jarapablo**, Hello!

This is not an error, as it should be. Arduino reads temperature from your thermocouple faster than temperature manages to change. Try running one with examples without delay (comment it) and quickly heat the thermocouple, such as a lighter. 

Also check for valid pin connection.

**Comment by jarapablo** [comment]
Hi YuriiSalimov,

I know it sounds odd but the temperature reading indeed gets stuck if no
delay is added... I tried several times and it gave me the same reading for
minutes (it never changes).. If I add the delay between readings then the
temperature changes and works as expected...

I am guessing the Arduino is faster than the thermocouple’s buffer or SPI
or something like that, but I still have to do some additional research to
see if I can figure it out myself...

Thank you!

**Comment by LucianGVx** [comment]
I had the same bug in the Average example, i  change delay (100) to delay (250).. now is working.

Thanks for the library.
