### ISSUE TITLE
How to know when thermocuple is failing or non connected

### ISSUE THREAD

**Issue by dragoblaztr** [YuriiSalimov/MAX6675_Thermocouple#2]
It's possible to know if module board or thermocouple itself is non or wrong connected or failing, cause when it's non connected at all readings returned are 0 degrees Celcius.

Thanks in advanced

**Comment by dragoblaztr** [comment]
Hi closed with no explanation or reminder where I can find that method and so on?

**Comment by YuriiSalimov** [comment]
It's not possible. Read datashit.
